import { compileTerminalPayoff, type CompileTerminalPayoffRequest, type ExecutableBinaryInstrument } from "@contour/compiler";
import { assetSymbol, DecimalAmount, outcomeId, UtcTimestamp, type BinaryPriceOutcome, type MarketFreshness, type OrderBookSnapshot } from "@contour/domain";
import { executionSnapshot, knownHip4ProtocolFee, outcomeMetadataForRequest, planExecution } from "@contour/execution";
import type { PerpetualTerminalComponent } from "@contour/payoff";

const d = (value: string) => DecimalAmount.parse(value); const btc = assetSymbol("BTC");
const settlement = UtcTimestamp.parse("2026-10-01T00:00:00Z"); const observedAt = UtcTimestamp.parse("2026-09-30T23:59:30Z"); const checkedAt = UtcTimestamp.parse("2026-10-01T00:00:00Z");
const freshness: MarketFreshness = { network: "mainnet", source: "hyperliquid-direct", observedAt };
function book(id: string, sideIndex: 0 | 1, asks: readonly [string, string][]): OrderBookSnapshot { return { outcomeId: outcomeId(id), sideIndex, coin: `#${10n * BigInt(id) + BigInt(sideIndex)}`, bids: [], asks: asks.map(([price, quantity]) => ({ price: d(price), quantity: d(quantity), orderCount: 1 })), freshness }; }
function market(id: string, threshold: string, noQuantity: string): ExecutableBinaryInstrument { const marketId = outcomeId(id); const normalized: BinaryPriceOutcome = { kind: "binaryPrice", id: marketId, underlying: btc, settlementAt: settlement, threshold: d(threshold), comparator: "greaterThan", yesSide: "yes", noSide: "no", sourceName: "execution fixture", freshness, protocol: { outcomeId: marketId, yesCoin: `#${10n * BigInt(id)}`, noCoin: `#${10n * BigInt(id) + 1n}`, yesAssetId: `${100_000_000n + 10n * BigInt(id)}`, noAssetId: `${100_000_001n + 10n * BigInt(id)}` } }; return { market: normalized, yesBook: book(id, 0, [["0.8", "100"]]), noBook: book(id, 1, [["0.1", noQuantity]]) }; }
const existing: PerpetualTerminalComponent = { kind: "perpetual", asset: btc, direction: "long", quantity: d("1"), entryPrice: d("100"), externalTerms: "excluded" };
const request: CompileTerminalPayoffRequest = { existingPortfolio: { components: [existing] }, settlement: { underlying: btc, timestamp: settlement, priceRange: { min: d("0"), max: d("100") } }, constraint: { minimumTerminalPnl: d("-40") }, maximumAcquisitionCost: d("100"), instruments: [market("101", "25", "30"), market("102", "50", "30"), market("103", "75", "40")], policy: { maximumBookAgeMs: 60_000, compilationTime: checkedAt, feeModel: { kind: "excluded" } } };
const compiled = await compileTerminalPayoff(request); const snapshot = executionSnapshot(request);
const result = planExecution({ request, compilerResult: compiled, requestIdentity: "contour-execution-fixture-v1", compilerSnapshotIdentity: snapshot.identity, protocolMetadata: outcomeMetadataForRequest(request, { precision: { kind: "KNOWN", szDecimals: 2, source: "deterministic probe metadata" }, observedAt }), protocolFee: knownHip4ProtocolFee(observedAt), checkedAt, maximumBookAgeMs: 45_000, trustPolicy: "DEVELOPMENT_DRY_RUN" });
console.log("CONTOUR EXECUTION — FIXTURE DRY RUN"); console.log(`Compiler: ${compiled.status}`); console.log(`Execution: ${result.status}`);
if (result.status !== "READY") { console.log(JSON.stringify(result, null, 2)); process.exitCode = 1; }
else { console.log(result.plan.report.text); const changed = result.plan.orders.some((order) => compiled.status === "FEASIBLE" && compiled.executionSegments.some((segment) => segment.marketId === order.marketId && segment.side === order.side && segment.quantity.compare(order.plannedQuantity) !== 0)); console.log(`Nontrivial quantity rounding: ${changed ? "PASS" : "FAIL"}`); if (!changed || !result.plan.verification.holds) process.exitCode = 1; }
