import { StatusPill } from "../../components/status-pill";
import { getLiveUniverse } from "../../lib/server/live";
import { formatBtcPrice, formatUtc } from "../../lib/presentation/format";

export const dynamic = "force-dynamic";
export default async function SystemPage(): Promise<React.JSX.Element> {
  const universe = await getLiveUniverse();
  return <main className="system-shell"><header className="topbar"><div><a className="wordmark" href="/">CONTOUR</a><p>System status · BUILD 03</p></div><nav><a href="/">Terminal</a><span className="readonly">READ-ONLY</span></nav></header><section className="system-grid"><div><p className="eyebrow">ENGINEERING STATUS · BUILD 03</p><h1>Protocol and compiler availability</h1><p className="system-copy">This page reports public read-only integration state. It never exposes credentials or wallet capabilities.</p></div><section className="panel"><div className="panel-heading"><h2>Hyperliquid mainnet</h2><StatusPill value={universe.freshness.state} /></div><dl className="metric-list"><div><dt>BTC perpetual read</dt><dd>{universe.btcMark ? `Mark ${formatBtcPrice(universe.btcMark)} · Oracle ${formatBtcPrice(universe.btcOracle ?? "0")}` : "Unavailable"}</dd></div><div><dt>HIP-4 discovery</dt><dd>{universe.supportedBinaryCount} supported BTC binaries</dd></div><div><dt>Settlement groups</dt><dd>{universe.settlementGroups.length}</dd></div><div><dt>Last successful observation</dt><dd>{universe.freshness.observedAt ? formatUtc(universe.freshness.observedAt) : "—"}</dd></div><div><dt>Compiler</dt><dd>Available · server-side</dd></div><div><dt>Exact verifier</dt><dd>Available · authoritative</dd></div><div><dt>Execution planner</dt><dd>Dry run · snapshot-bound</dd></div><div><dt>Live size precision</dt><dd>Blocked when outcomeMeta omits szDecimals</dd></div></dl>{universe.unavailableReason && <p className="notice error-notice">{universe.unavailableReason}</p>}</section></section></main>;
}
