import { StatusPill } from "../../components/status-pill";
import { getLiveUniverse } from "../../lib/server/live";
import { formatBtcPrice, formatUtc } from "../../lib/presentation/format";
import { buildIdentity } from "../../lib/server/build-identity";

export const dynamic = "force-dynamic";
export default async function SystemPage(): Promise<React.JSX.Element> {
  const universe = await getLiveUniverse();
  const sourceState = universe.freshness.state;
  return <main className="system-shell"><header className="topbar"><div><a className="wordmark" href="/">CONTOUR</a><p>System status · {buildIdentity.build}</p></div><nav><a href="/">Terminal</a><span className="readonly">READ-ONLY</span></nav></header><section className="system-grid"><div><p className="eyebrow">ENGINEERING STATUS · {buildIdentity.build}</p><h1>Protocol and compiler availability</h1><p className="system-copy">Public read-only integration status. Live reads may be temporarily unavailable; the deterministic demo is local and remains usable. No credentials or wallet capabilities are involved.</p><p className="system-copy">Build revision: <code>{buildIdentity.revision}</code></p></div><section className="panel"><div className="panel-heading"><h2>Hyperliquid mainnet</h2><StatusPill value={sourceState} /></div><dl className="metric-list"><div><dt>BTC perpetual read</dt><dd>{universe.btcMark ? `Mark ${formatBtcPrice(universe.btcMark)} · Oracle ${formatBtcPrice(universe.btcOracle ?? "0")}` : "Unavailable"}</dd></div><div><dt>HIP-4 discovery</dt><dd>{universe.supportedBinaryCount} supported BTC binaries</dd></div><div><dt>Settlement groups</dt><dd>{universe.settlementGroups.length}</dd></div><div><dt>Last successful observation</dt><dd>{universe.freshness.observedAt ? formatUtc(universe.freshness.observedAt) : "—"}</dd></div><div><dt>Compiler</dt><dd>Available · server-side</dd></div><div><dt>Exact verifier</dt><dd>Available · authoritative</dd></div><div><dt>Execution planner</dt><dd>Dry run · snapshot-bound</dd></div><div><dt>Live size precision</dt><dd>Strict mainnet remains blocked when required protocol evidence is unresolved.</dd></div><div><dt>Health endpoint</dt><dd><a href="/api/health">/api/health</a></dd></div></dl>{universe.unavailableReason && <p className="notice error-notice" role="status">{universe.unavailableReason}</p>}</section></section></main>;
}
